Repository codestates-seb/seb39_main_059, pull requests merged in 2022-11, with the labels that each got.

#304 [FE] 냥이생활 좋아요 추가/취소 기능 구현
  client/src/pages/Feed/Feeds/Feeds.tsx
  client/src/pages/Feed/NewFeed/NewFeed.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/Signup/Signup.tsx
  client/src/redux/actions/FeedsAction.ts
  client/src/redux/reducers/FeedsSlice.ts
Labels: ☀️ FE, 💡 FEAT, 🎯 REQUIRED

#307 fix: 배포용에선 SQL 로그 제거
  server/catvillage/src/main/resources-prod/application.yml
Labels: 🌕 BE, 🔧 FIX

#309 Feat/new boards
  client/src/@types/board.ts
  client/src/components/modules/TabBar/TabBar.tsx
  client/src/components/template/FeedForm/index.ts
  client/src/components/template/PostForm/PostForm.style.tsx
  client/src/components/template/PostForm/PostForm.tsx
  client/src/components/template/PostForm/index.ts
  client/src/pages/Board/Boards/Boards.style.tsx
  client/src/pages/Board/Boards/Boards.tsx
  client/src/pages/Board/Boards/Tab.style.tsx
  client/src/pages/Board/NewBoard/NewBoard.tsx
  client/src/pages/Feed/NewFeed/NewFeed.tsx
  client/src/redux/store/index.ts
Labels: ☀️ FE, 💡 FEAT, 🔧 FIX

#312 fix: Exception 에러 코드 수정
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/exception/ExceptionCode.java
Labels: 🌕 BE, 🔧 FIX

#316 feat: 고양이 품종 정보 조회(전체, 특정) API 구현
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/controller/CatInfoController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/dto/CatInfoPostDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/dto/CatInfoResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/dto/CatInfoSimpleDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/dto/DiseaseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/entity/CatInfo.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/mapper/CatInfoMapper.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/service/CatInfoService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/config/SwaggerConfig.java
Labels: 🌕 BE, 💡 FEAT, 🔧 FIX

#318 [FE] 로그인 상태 유지 기능 구현
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/index.tsx
  client/src/pages/Feed/Feeds/Feeds.tsx
  client/src/pages/Feed/NewFeed/NewFeed.tsx
  client/src/redux/reducers/FeedsSlice.ts
  client/src/redux/store/index.ts
Labels: ☀️ FE, 💡 FEAT, ⚙️ REFACTOR

#325 fix: picture에 유효성검증 정규표현식 버그 fix
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/picture/dto/PictureDto.java
Labels: 🌕 BE, 🐞 BUG

#326 fix: PostForm 전송 버튼 첫 클릭시 sumbmit이 제대로 수행되지 않는 현상 수정
  client/src/components/modules/ImageInput/ImageInput.tsx
  client/src/components/template/PostForm/PostForm.tsx
  client/src/pages/Board/NewBoard/NewBoard.tsx
Labels: ☀️ FE, 🔧 FIX

#330 fix: 냥이생활 피드 반환 데이터에 isMyFeed 데이터 추가
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/controller/FeedController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/dto/FeedGetResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/dto/FeedMultiGetResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/mapper/FeedMapper.java
Labels: 🌕 BE, 🔧 FIX

#331 feat: 냥이생활 피드 작성 시 로그인된 유저의 모든 고양이 프로필 정보를 받아오는 API 구현
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/config/SwaggerConfig.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/controller/FeedController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/dto/FeedMultiResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/controller/UserController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/UserCatResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/follow/FollowFeedGetDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/follow/FollowGetResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/follow/FollowResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/follow/FollowerResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/follow/FollowingResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/mapper/FollowMapper.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/mapper/UserMapper.java
Labels: 🌕 BE, 💡 FEAT, ⚙️ REFACTOR

#334 [FE] isLogin 상태 타입 에러에 해결 방법 적용
  client/src/pages/Feed/Feeds/Feeds.tsx
  client/src/redux/store/index.ts
Labels: ☀️ FE, 🔧 FIX

#336 feat: 집사생활 검색 기능 추가
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/controller/BoardController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/repository/BoardRepository.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/service/BoardService.java
Labels: 🌕 BE, 💡 FEAT

#337 feat: 집사생활 태그 CURD 추가
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/controller/BoardController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/entity/BoardTag.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/service/BoardTagService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/exception/ExceptionCode.java
Labels: 🌕 BE, 💡 FEAT

#340 [FE] 드롭다운 컴포넌트 생성
  client/src/@types/feed.ts
  client/src/assets/icons/dropdownMenu.svg
  client/src/assets/icons/index.tsx
  client/src/components/modules/Dropdown/Dropdown.styles.tsx
  client/src/components/modules/Dropdown/Dropdown.tsx
  client/src/components/modules/Dropdown/index.ts
  client/src/components/template/FeedDetail/FeedDetail.style.tsx
  client/src/components/template/FeedDetail/FeedDetail.tsx
  client/src/redux/reducers/FeedDetailSlice.ts
Labels: ☀️ FE, 💡 FEAT

#339 feat: 특정 유저가 좋아요 누른 냥이생활 피드 조회 API 구현(페이지네이션 적용)
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/like/LikeRepository.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/like/LikeService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/controller/FeedController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/service/FeedService.java
Labels: 🌕 BE, 💡 FEAT

#345 Feat/logout
  client/src/components/modules/TabBar/TabBar.tsx
  client/src/index.tsx
  client/src/pages/Profile/Profile.style.ts
  client/src/pages/Profile/Profile.tsx
  client/src/pages/Profile/index.ts
  client/src/redux/actions/userAction.ts
  client/src/redux/reducers/UserSlice.ts
  client/src/routes/AppRoutes.tsx
  client/src/routes/profile.routes.tsx
Labels: ☀️ FE, 💡 FEAT, 🎯 REQUIRED

#348 [FE] 폴더 정리
  client/src/assets/README.md
  client/src/components/README.md
  client/src/components/atoms/readme.md
  client/src/data/index.ts
  client/src/layout/readme.md
  client/src/pages/Board/Boards/Boards.tsx
  client/src/pages/Board/NewBoard/NewBoard.tsx
  client/src/pages/Home/index.tsx
  client/src/redux/actions/boardsAction.ts
  client/src/redux/actions/userAction.ts
  client/src/stores/store/README.md
Labels: ☀️ FE

#350 [FE] 냥이생활 피드 삭제 기능 구현
  client/src/components/modules/Dropdown/Dropdown.tsx
  client/src/components/template/FeedDetail/FeedDetail.tsx
Labels: ☀️ FE, 💡 FEAT, 🎯 REQUIRED

#351 fix: reissue request body에 accessToken 안받도록 API 변경
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/config/SecurityConfig.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/controller/AuthController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/dto/TokenDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/dto/TokenRequestDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/provider/JwtTokenizer.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/service/AuthService.java
Labels: 🌕 BE, 🔧 FIX

#354 [FE] 냥이생활 피드 작성 기능 추가
  client/src/pages/Feed/NewFeed/NewFeed.tsx
  client/src/redux/actions/FeedDetailAction.ts
Labels: ☀️ FE, 💡 FEAT

#359 Refactor: axios instance
  client/src/api/auth.ts
  client/src/components/template/FeedDetail/FeedDetail.tsx
  client/src/components/template/PostForm/PostForm.tsx
  client/src/pages/Board/NewBoard/NewBoard.tsx
  client/src/pages/Cat/Cat.tsx
  client/src/pages/Feed/NewFeed/NewFeed.tsx
  client/src/redux/actions/FeedDetailAction.ts
  client/src/redux/actions/FeedsAction.ts
  client/src/redux/actions/boardsAction.ts
  client/src/redux/actions/userAction.ts
  client/src/utils/instance.ts
  client/src/utils/tokenControl.ts
Labels: ☀️ FE, ⚙️ REFACTOR
