Repository codestates-seb/seb39_main_059, pull requests merged in 2022-10, with the labels that each got.

#174 feat: 냥이생활 글 수정하기 기능 구현
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/controller/FeedController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/entity/Feed.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/repository/FeedTagRepository.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/service/FeedService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/service/FeedTagService.java
Labels: 🌕 BE, 💡 FEAT, 🎯 REQUIRED

#178 feat: health check controller 추가
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/health_check/HealthCheckController.java
Labels: 🌕 BE, 🖥 DEPLOY, 💡 FEAT

#175 feat: 일반 회원가입 구현
  client/.eslintrc.js
  client/src/@types/user.ts
  client/src/App.tsx
  client/src/pages/Signup/Signup.tsx
  client/src/redux/actions/userAction.ts
  client/src/redux/reducers/userSlice.ts
  client/src/redux/store/index.ts
  client/src/utils/instance.ts
Labels: ☀️ FE, 💡 FEAT

#181 fix: 배포 action시 환경변수 생성 문제로 실패하던 문제 해결
  .github/workflows/client-auto-deploy.yml
  client/.gitignore
  client/env/.env.example
Labels: 🐞 BUG, 🖥 DEPLOY, ☀️ FE

#184 fix: Kakao OAuth2 로그인 적용
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/CustomOAuth2UserService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/OAuthAttributes.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/config/SecurityConfig.java
  server/catvillage/src/main/resources-prod/application.yml
  server/catvillage/src/main/resources/application-common.yml
Labels: 🌕 BE, 🔧 FIX

#187 feat: swagger response 추가
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/controller/BoardController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/controller/CatController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/health_check/HealthCheckController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/picture/controller/FileUploadController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/config/SwaggerConfig.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/dto/MultiBoardResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/exception/ExceptionCode.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/controller/FeedController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/controller/AuthController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/controller/UserController.java
Labels: 🌕 BE, 💡 FEAT

#188 feat: 냥이생활 글 삭제하기 기능 구현 및 고양이 삭제시 유저 검증 로직 추가
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/controller/CatController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/service/CatService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/controller/FeedController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/service/FeedService.java
Labels: 🌕 BE, 💡 FEAT, 🔧 FIX

#190 feat: 로그인 후 유저 기본정보 가져오는 API 구현
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/CustomOAuth2UserService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/controller/UserController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/UserMyInfoDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/mapper/UserMapper.java
Labels: 🌕 BE, 💡 FEAT

#193 fix: Swagger API docs에 UserMyInfoDto 적용 안되는 문제 fix
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/config/SwaggerConfig.java
Labels: 🌕 BE, 🐞 BUG

#192 fix: 냥이생활 피드 작성하기 및 수정하기 기능 bug fix
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/picture/entity/Picture.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/controller/FeedController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/mapper/FeedMapper.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/service/FeedService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/service/FeedTagService.java
Labels: 🌕 BE, 🐞 BUG

#195 fix: 고양이 등록하기, 수정하기 및 유저 정보 수정하기 기능 오류 fix
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/controller/CatController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/entity/Cat.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/mapper/CatMapper.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/service/CatService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/service/CatTagService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/controller/UserController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/service/UserService.java
Labels: 🌕 BE, 🐞 BUG

#197 feat: 일반 로그인 기능 구현
  client/src/@types/user.ts
  client/src/pages/Login/Login.tsx
  client/src/redux/actions/userAction.ts
  client/src/redux/reducers/userSlice.ts
Labels: ☀️ FE, 💡 FEAT, 🎯 REQUIRED

#198 Feat: 앱 화면 크기를 원하는 화면 크기로 사용할 수 있는 기능 추가
  client/src/layout/DashBoard.tsx
  client/src/layout/Iphone11ProLayout.tsx
  client/src/layout/PhoneLayout.tsx
Labels: ☀️ FE, 💡 FEAT

#201 Feat: main페이지 layout제작
  client/src/layout/MainLayout.tsx
  client/src/layout/PhoneLayout.tsx
  client/src/routes/AppRoutes.tsx
  client/src/routes/board.routes.tsx
  client/src/routes/feed.routes.tsx
  client/src/routes/index.ts
  client/src/routes/main.routes.tsx
Labels: ☀️ FE, 💡 FEAT

#202 feat: logout 추가
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/exception/ExceptionCode.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/controller/AuthController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/refreshToken/RefreshTokenRepository.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/service/AuthService.java
Labels: 🌕 BE, 💡 FEAT, 🎯 REQUIRED

#203 feat: 냥이생활 댓글 작성, 수정, 삭제 기능 구현
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/entity/Cat.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/config/SwaggerConfig.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/exception/ExceptionCode.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/controller/FeedController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/dto/FeedCommentGetDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/dto/FeedCommentPatchDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/dto/FeedCommentPostDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/entity/Feed.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/entity/FeedComment.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/mapper/FeedCommentMapper.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/service/FeedCommentService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/entity/User.java
Labels: 🌕 BE, 💡 FEAT, 🎯 REQUIRED

#204 feat: 집사생활 댓글 등록, 수정, 삭제, 조회 추가
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/controller/BoardController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/BoardGetResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/comment/BoardCommentPatchDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/comment/BoardCommentPostDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/comment/BoardCommentPostResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/comment/BoardCommentResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/comment/BoardUserCommentResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/entity/BoardComment.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/mapper/BoardCommentMapper.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/service/BoardCommentService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/config/SwaggerConfig.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/exception/ExceptionCode.java
Labels: 🌕 BE, 💡 FEAT, 🎯 REQUIRED

#214 fix: allowed origin 수정
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/config/CorsConfig.java
Labels: 🌕 BE, 🔧 FIX

#215 fix: 로그인 시 입력정보 username에서 email로 변경
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/controller/AuthController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/dto/UserRequestDto.java
Labels: 🌕 BE, 🐞 BUG, 🔧 FIX

#216 fix: 유저 정보 변경 및 탈퇴 기능 수정
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/controller/UserController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/service/UserService.java
Labels: 🌕 BE, 🔧 FIX

#219 fix: security 제공 logout 비활성화
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/config/SecurityConfig.java
Labels: 🌕 BE, 🔧 FIX

#221 fix: 집사생활 request body 수정
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/controller/BoardController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/BoardPatchDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/BoardPostDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/BoardPostResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/mapper/BoardMapper.java
Labels: 🌕 BE, 💡 FEAT

#222 feat: business logic exception handler 추가
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/exception/ExceptionCode.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/exception/config/BusinessLogicExceptionHandler.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/exception/dto/ErrorResponse.java
Labels: 🌕 BE, 💡 FEAT

#223 feat: 고양이 품종정보 필수 클래스 구현 및 등록하기 기능 구현
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/entity/Cat.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/mapper/CatMapper.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/service/CatService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/controller/CatInfoController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/dto/CatInfoGetResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/dto/CatInfoPostDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/dto/CatInfoResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/entity/CatInfo.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/entity/Disease.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/entity/DiseaseToCat.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/entity/DiseaseToCatId.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/mapper/CatInfoMapper.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/repository/CatInfoRepository.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/repository/DiseaseRepository.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/repository/DiseaseToCatRepository.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/service/CatInfoService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/exception/ExceptionCode.java
Labels: 🌕 BE, 💡 FEAT

#226 fix: 집사생활 등록 및 수정 시 에러 수정
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/controller/BoardController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/BoardGetResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/BoardPatchDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/BoardPostDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/comment/BoardCommentResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/mapper/BoardCommentMapper.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/service/BoardService.java
Labels: 🌕 BE, 🔧 FIX

#225 feat: Swagger에 Post-Cat 요청 dto에 대한 설명 작성
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/dto/CatPostDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/dto/CatTagPostDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/config/SwaggerConfig.java
Labels: 🌕 BE, 📄 DOCS

#229 fix: tagName 칼럼에 Unique 속성 추가
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/entity/BoardTag.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/entity/CatTag.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/entity/CatInfo.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/entity/Disease.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/entity/FeedTag.java
Labels: 🌕 BE, 🔧 FIX

#230 feat: like 필수 클래스 구현 및 서비스 구현
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/entity/Board.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/entity/BoardComment.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/like/Like.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/like/LikeRepository.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/like/LikeService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/entity/Feed.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/entity/FeedComment.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/entity/User.java
Labels: 🌕 BE, 💡 FEAT, 🎯 REQUIRED

#234 [FE] 냥이생활 전체 피드 페이지 데이터 불러오는 로직 구현
  client/src/@types/feed.ts
  client/src/pages/Feed/Feeds/Feeds.style.ts
  client/src/pages/Feed/Feeds/Feeds.tsx
  client/src/redux/actions/FeedsAction.ts
  client/src/redux/reducers/FeedSlice.ts
  client/src/redux/store/index.ts
Labels: ☀️ FE, 💡 FEAT, 🎯 REQUIRED

#235 feat: 팔로우 및 언팔로우 기능, 팔로우 및 팔로워 조회 기능 추가
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/config/SwaggerConfig.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/exception/ExceptionCode.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/service/FeedService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/controller/FollowService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/controller/UserController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/FollowGetResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/FollowResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/FollowerResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/FollowingResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/entity/Follow.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/entity/User.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/mapper/FollowMapper.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/repository/FollowRepository.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/service/FollowService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/service/UserService.java
Labels: 🌕 BE, 💡 FEAT

#238 Feat: 고양이 생성하기 페이지 formdata 가져오기 구현
  client/src/assets/icons/back.svg
  client/src/assets/icons/edit.svg
  client/src/assets/icons/index.tsx
  client/src/components/atoms/Input/Input.tsx
  client/src/components/atoms/Text/Text.style.tsx
  client/src/components/atoms/Text/Text.tsx
  client/src/components/atoms/Text/index.ts
  client/src/components/modules/FormTextInput/FormTextInput.tsx
  client/src/components/modules/ImageInput/ImageInput.style.tsx
  client/src/components/modules/ImageInput/ImageInput.tsx
  client/src/components/modules/TabBar/TabBar.style.ts
  client/src/components/modules/TabBar/TabBar.tsx
  client/src/constant/index.ts
  client/src/layout/DashBoard.tsx
  client/src/pages/Cat/Cat.style.tsx
  client/src/pages/Cat/Cat.tsx
  client/src/pages/Cat/index.ts
  client/src/routes/AppRoutes.tsx
  client/src/styles/GlobalStyle.ts
  client/src/utils/utility.tsx
  client/webpack/webpack.dev.js
Labels: 💡 FEAT

#240 fix: 냥이생활 특정 피드 보기에 변수 수정 및 피드 반환 데이터에 좋아요 데이터 추가
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/like/LikeService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/controller/FeedController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/dto/FeedCommentGetDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/dto/FeedGetResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/dto/FeedMultiGetResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/mapper/FeedCommentMapper.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/mapper/FeedMapper.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/service/FeedService.java
Labels: 🌕 BE, 🔧 FIX

#243 fix: local test를 위한 cors origin 추가
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/config/CorsConfig.java
Labels: 🌕 BE, 🔧 FIX, 🧪 TEST

#244 fix: 이미지 저장용 S3 버킷 이동으로 버킷 이름 수정
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/picture/service/S3UploadService.java
  server/catvillage/src/main/resources/application-common.yml
Labels: 🌕 BE, 🔧 FIX

#246 fix: 기본 프로필 이미지 적용
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/mapper/UserMapper.java
Labels: 🌕 BE, 🔧 FIX

#247 fix: 유저 정보 변경 시 기본 프로필 이미지 설정
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/mapper/UserMapper.java
Labels: 🌕 BE, 🔧 FIX

#248 [FE] 냥이생활 특정 피드 구현
  client/src/@types/feed.ts
  client/src/components/template/FeedDetail/FeedDetail.tsx
  client/src/pages/Feed/FeedDetail/FeedDetail.tsx
  client/src/pages/Feed/Feeds/Feeds.tsx
  client/src/redux/actions/FeedDetailAction.ts
  client/src/redux/reducers/FeedDetailSlice.ts
  client/src/redux/reducers/FeedsSlice.ts
  client/src/redux/store/index.ts
Labels: ☀️ FE, 💡 FEAT, 🎯 REQUIRED

#254 fix: 회원가입 시 null pointer exception 해결
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/mapper/UserMapper.java
Labels: 🌕 BE, 🔧 FIX

#255 fix: 냥이생활 피드 수정하기 시 사진 저장되지 않는 오류 fix
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/service/FeedService.java
Labels: 🌕 BE, 🐞 BUG

#256 fix: 집사생활 조회 시 사진 로직 수정
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/mapper/BoardMapper.java
Labels: 🌕 BE, 🔧 FIX

#260 feat: 댓글 컴포넌트 수정 밎 댓글 템플릿 생성
  client/src/components/atoms/Comment/Comment.style.ts
  client/src/components/atoms/Comment/Comment.tsx
  client/src/components/template/Comments/Comments.style.tsx
  client/src/components/template/Comments/index.ts
  client/src/components/template/FeedDetail/FeedDetail.style.tsx
  client/src/components/template/FeedDetail/FeedDetail.tsx
Labels: ☀️ FE, 💡 FEAT

#261 Feat: 로그인 관련 페이지에 서비스 로고 추가
  client/public/index.html
  client/public/manifest.json
  client/src/assets/logo.svg
  client/src/pages/Login/Login.style.ts
  client/src/pages/Login/Login.tsx
  client/src/pages/Signup/Signup.style.ts
  client/src/pages/Signup/Signup.tsx
Labels: ☀️ FE, 💄 STYLE

#262 feat: app layout을 발표용 layout으로 변경
  client/src/layout/DashBoard.tsx
  client/src/layout/PhoneLayout.tsx
  client/src/layout/PresentLayout.tsx
  client/src/routes/AppRoutes.tsx
Labels: ☀️ FE, 💡 FEAT, 💄 STYLE

#264 feat: 고양이 프로필 기본 이미지 자동 할당
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/mapper/CatMapper.java
Labels: 🌕 BE, 🔧 FIX

#266 Feat: favicon 적용
  client/public/favicon.ico
  client/public/logo192.png
  client/public/logo512.png
Labels: ☀️ FE, 💄 STYLE

#267 fix: 집사생활 댓글 반환 데이터 수정
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/comment/BoardCommentResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/mapper/BoardCommentMapper.java
Labels: 🌕 BE, 🔧 FIX

#268 fix: 집사생활 게시글 반환 데이터 수정
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/BoardGetResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/BoardMultiGetResponse.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/mapper/BoardMapper.java
Labels: 🌕 BE, 🔧 FIX

#275 fix: user 테이블 칼럼 추가로 엔티티에 변수 추가 및 유저 프로필 페이지에 필요한 dto 생성
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/dto/CatResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/dto/CatSimpleDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/mapper/CatMapper.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/dto/FeedSimpleDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/mapper/FeedMapper.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/UserGetResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/entity/User.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/mapper/UserMapper.java
Labels: 🌕 BE, 🔧 FIX

#276 [FE] 댓글 리팩토링
  client/src/@types/feed.ts
  client/src/components/template/Comments/Comments.tsx
  client/src/components/template/FeedDetail/FeedDetail.tsx
  client/src/pages/Feed/FeedDetail/FeedDetail.tsx
Labels: 💡 FEAT, ⚙️ REFACTOR, 🎯 REQUIRED

#279 feat: 유저 ID로 고양이 정보 불러오는 API 구현
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/controller/CatController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/dto/CatUserResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/mapper/CatMapper.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/service/CatService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/config/SwaggerConfig.java
Labels: 🌕 BE, 🔧 FIX

#281 fix: SwaggerConfig 수정
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/config/SwaggerConfig.java
Labels: 🌕 BE, 🐞 BUG, 📄 DOCS

#282 style: Noto Sans KR 폰트 적용 및 냥이생활 관련 컴포넌트 스타일링 수정
  client/public/index.html
  client/src/assets/icons/emptyHeart.svg
  client/src/assets/icons/index.tsx
  client/src/components/atoms/Comment/Comment.style.ts
  client/src/components/template/Comments/Comments.style.tsx
  client/src/components/template/FeedDetail/FeedDetail.style.tsx
  client/src/components/template/FeedForm/FeedForm.style.tsx
  client/src/pages/Feed/FeedDetail/FeedDetail.tsx
  client/src/pages/Feed/Feeds/Feeds.tsx
  client/src/styles/theme.ts
Labels: ☀️ FE, 💄 STYLE

#283 Feat: 집사생활 게시글 모아보기 페이지 작성
  client/src/@types/board.ts
  client/src/components/modules/TabBar/TabBar.style.ts
  client/src/data/index.ts
  client/src/layout/MainLayout.tsx
  client/src/pages/Board/Boards/BoardView.style.tsx
  client/src/pages/Board/Boards/BoardView.tsx
  client/src/pages/Board/Boards/Boards.style.tsx
  client/src/pages/Board/Boards/Boards.tsx
  client/src/pages/Board/Boards/BreedSelection.style.tsx
  client/src/pages/Board/Boards/BreedSelection.tsx
  client/src/pages/Board/Boards/Tab.style.tsx
  client/src/pages/Board/Boards/Tab.tsx
  client/src/redux/actions/boardsAction.ts
  client/src/redux/reducers/BoardsSlice.ts
  client/src/redux/store/index.ts
Labels: ☀️ FE, 💡 FEAT, 🎯 REQUIRED

#284 feat: s3 파일 삭제 기능 구현
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/picture/controller/FileUploadController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/picture/service/S3UploadService.java
Labels: 🌕 BE, 💡 FEAT

#285 fix: 냥이생활 관련 수정
  client/src/@types/feed.ts
  client/src/components/modules/ImageInput/ImageInput.style.tsx
  client/src/components/template/FeedDetail/FeedDetail.style.tsx
  client/src/components/template/FeedDetail/FeedDetail.tsx
  client/src/components/template/FeedForm/FeedForm.style.tsx
  client/src/pages/Feed/Feeds/Feeds.tsx
  client/src/pages/Feed/NewFeed/NewFeed.tsx
Labels: ☀️ FE, 🔧 FIX

#287 feat: 냥이생활 전체 피드 좋아요 구현
  client/src/components/template/FeedForm/FeedForm.tsx
  client/src/pages/Feed/Feeds/Feeds.tsx
  client/src/redux/reducers/FeedsSlice.ts
Labels: ☀️ FE, 💡 FEAT

#288 fix: 냥이생활 피드 작성 페이지 수정
  client/src/components/modules/FormTextInput/FormTextInput.tsx
  client/src/components/template/FeedForm/FeedForm.tsx
  client/src/pages/Feed/NewFeed/NewFeed.tsx
  client/src/pages/Page404/index.tsx
Labels: ☀️ FE, 💡 FEAT, 🔧 FIX

#290 feat: 특정 유저가 작성한 피드 불러오는 API 구현
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/config/SwaggerConfig.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/controller/FeedController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/repository/FeedRepository.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/service/FeedService.java
Labels: 🌕 BE, 💡 FEAT

#291 fix: 집사생활 전체 게시글 조회 버그 수정
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/mapper/BoardMapper.java
Labels: 🌕 BE, 🔧 FIX

#297 fix: picture 및 tag의 유효성 검증 추가, tag NPE 버그 fix
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/BoardPatchDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/BoardPostDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/picture/dto/PictureDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/dto/FeedPostDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/service/FeedTagService.java
  server/catvillage/src/main/resources-prod/application.yml
  server/catvillage/src/main/resources/application-common.yml
Labels: 🌕 BE, 🐞 BUG, 🔧 FIX

#302 feat: 대표 고양이 설정 API 구현
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/controller/CatController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/service/CatService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/service/UserService.java
Labels: 🌕 BE, 💡 FEAT
