Repository codestates-seb/seb39_main_059, pull requests merged in 2022-09, with the labels that each got.

#25 chore: 프론트엔드 초기 세팅
  client/.babelrc
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/@types/react-app-env.d.ts
  client/src/App.css
  client/src/App.tsx
  client/src/index.css
  client/src/index.tsx
  client/src/logo.svg
  client/tsconfig.json
  client/webpack.config.js
  client/webpack/webpack.common.js
  client/webpack/webpack.dev.js
  client/webpack/webpack.prod.js
Labels: ☀️ FE, 💡 FEAT

#26 chore: 기본적인 폴더 구조 생성
  client/src/App.tsx
  client/src/api/README.md
  client/src/assets/README.md
  client/src/assets/logo.svg
  client/src/components/README.md
  client/src/hooks/useInput.ts
  client/src/layout/readme.md
  client/src/pages/Home/index.tsx
  client/src/pages/Page404/index.tsx
  client/src/pages/Page500/index.tsx
  client/src/routes/routes.ts
  client/src/stores/store/README.md
  client/src/styles/readme.md
  client/src/utils/utility.tsx
Labels: ☀️ FE, 💡 FEAT

#28 chore: eslint 설정
  client/.eslintrc.js
  client/.prettierrc.js
  client/package-lock.json
  client/package.json
  client/src/@types/react-app-env.d.ts
  client/src/App.tsx
  client/src/index.tsx
  client/tsconfig.json
Labels: ☀️ FE, 💡 FEAT

#29 Feat/eslint
  client/.eslintrc.js
  client/package.json
  client/src/@types/react-app-env.d.ts
  client/src/App.tsx
  client/src/hooks/useInput.ts
  client/src/index.tsx
  client/src/pages/Home/index.tsx
  client/src/pages/Page404/index.tsx
  client/src/pages/Page500/index.tsx
  client/src/routes/routes.ts
  client/src/utils/utility.tsx
Labels: ☀️ FE, 🔧 FIX

#30 style: GlobalStyle 적용
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.tsx
  client/src/index.css
  client/src/index.tsx
  client/src/styles/GlobalStyle.ts
  client/src/styles/readme.md
Labels: ☀️ FE, 💄 STYLE

#35 feat: date audit table 추가
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/CatvillageApplication.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/audit/DateTable.java
Labels: 🌕 BE, 🎯 REQUIRED

#36 feat: custom bean utils 추가
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/utils/CustomBeanUtils.java
Labels: 🌕 BE, 💡 FEAT

#38 feat: global exception 처리 클래스 구현
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/exception/BusinessLogicException.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/exception/ExceptionCode.java
Labels: 🌕 BE, 💡 FEAT

#39 feat: user 필수 클래스 구현
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/controller/UserController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/UserResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/entity/User.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/mapper/UserMapper.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/repository/UserRepository.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/service/UserService.java
Labels: 🌕 BE, 💡 FEAT, 🎯 REQUIRED

#43 feat: 특정 고양이 프로필 보기 기능 구현
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/controller/CatController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/dto/CatPostDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/dto/CatResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/dto/CatTagPostDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/dto/CatTagResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/entity/Cat.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/mapper/CatMapper.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/mapper/CatTagMapper.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/service/CatService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/exception/ExceptionCode.java
Labels: 🌕 BE, 💡 FEAT, 🎯 REQUIRED

#45 fix: date table 변수 타입 수정
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/audit/DateTable.java
Labels: 🌕 BE, 🔧 FIX

#46 style: 공통 레이아웃 설정
  client/src/styles/GlobalStyle.ts
  client/src/styles/Iphone11ProContainer.tsx
Labels: ☀️ FE, 💄 STYLE

#50 fix: user의 name 컬럼에 unique 적용
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/entity/User.java
Labels: 🌕 BE, 🔧 FIX

#53 feat: 일반 회원가입 및 이름 중복 검사 기능 구현
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/exception/ExceptionCode.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/controller/UserController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/UserPostDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/UserPostResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/UserResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/entity/User.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/mapper/UserMapper.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/repository/UserRepository.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/service/UserService.java
Labels: 🌕 BE, 💡 FEAT, 🎯 REQUIRED

#52 feat: 고양이 품종 전체보기, 추가하기, 삭제하기 기능 구현
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/controller/CatController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/dto/BreedPostDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/dto/BreedResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/entity/Breed.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/mapper/BreedMapper.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/service/BreedService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/service/CatService.java
Labels: 🌕 BE, 💡 FEAT

#57 feat: APP_API를 환경 변수에 추가
  client/env/.env.dev
  client/env/.env.prod
  client/webpack/webpack.common.js
Labels: ☀️ FE, 💡 FEAT

#59 style: 공통 스타일 속성 관리를 위한 theme 설정
  client/src/@types/styled.d.ts
  client/src/App.tsx
  client/src/styles/GlobalStyle.ts
  client/src/styles/Iphone11ProContainer.tsx
  client/src/styles/theme.ts
Labels: ☀️ FE, 🔧 FIX, 💄 STYLE

#60 fix: path alias 이름 수정
  client/package-lock.json
  client/package.json
  client/tsconfig.json
  client/webpack/webpack.common.js
Labels: ☀️ FE, 🔧 FIX

#64 fix: TagToCat PK 2개 오류 fix
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/entity/TagToCat.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/entity/TagToCatId.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/service/CatService.java
Labels: 🌕 BE, 🐞 BUG

#66 chore: 배포 자동화 설정 파일 생성
  .github/workflows/auto-build.yml
  appspec.yml
  scripts/deploy.sh
Labels: 🌕 BE, 🖥 DEPLOY

#67 chore: script에서 jar 경로 변경
  scripts/deploy.sh
Labels: 🌕 BE, 🖥 DEPLOY

#71 feat: 유저 정보 보기, 변경, 회원 탈퇴 및 follow entity 추가
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/controller/UserController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/UserGetResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/UserPatchDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/UserPatchResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/entity/Follow.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/entity/User.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/mapper/UserMapper.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/service/UserService.java
Labels: 🌕 BE, 💡 FEAT, 🎯 REQUIRED

#83 fix: lint 관련 수정사항 반영
  client/.eslintrc.js
  client/.prettierrc.js
  client/tsconfig.json
Labels: ☀️ FE, 🔧 FIX

#84 feat: 카카오 OAuth2 인증을 위한 코드 추가
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/CustomOAuth2UserService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/OAuthAttributes.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/SessionUser.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/entity/User.java
Labels: 🌕 BE, 💡 FEAT

#89 Feat: atoms 컴포넌트 작성
  client/src/@types/react-app-env.d.ts
  client/src/@types/styled.d.ts
  client/src/components/atoms/Avatar/Avatar.style.ts
  client/src/components/atoms/Avatar/Avatar.tsx
  client/src/components/atoms/Avatar/index.ts
  client/src/components/atoms/Button/Button.style.ts
  client/src/components/atoms/Button/Button.tsx
  client/src/components/atoms/Button/index.tsx
  client/src/components/atoms/Comment/Comment.style.ts
  client/src/components/atoms/Comment/Comment.tsx
  client/src/components/atoms/Comment/index.ts
  client/src/components/atoms/Image/Image.tsx
  client/src/components/atoms/Image/index.tsx
  client/src/components/atoms/Input/Input.style.ts
  client/src/components/atoms/Input/Input.tsx
  client/src/components/atoms/Input/index.ts
  client/src/components/atoms/SvgButton/SvgButton.style.ts
  client/src/components/atoms/SvgButton/SvgButton.tsx
  client/src/components/atoms/SvgButton/index.tsx
  client/src/components/atoms/TextArea/TextArea.tsx
  client/src/components/atoms/TextArea/index.tsx
  client/src/styles/theme.ts
  client/src/utils/utility.tsx
Labels: ☀️ FE, 💡 FEAT

#87 feat: spring security 설정과 JWT 기능 구현
  .github/workflows/PR-build.yml
  .github/workflows/auto-build.yml
  server/catvillage/build.gradle
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/OAuthAttributes.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/config/CorsConfig.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/config/JwtSecurityConfig.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/config/SecurityConfig.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/controller/AuthController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/dto/TokenDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/dto/TokenRequestDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/dto/UserRequestDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/filter/JwtAccessDeniedHandler.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/filter/JwtAuthenticationEntryPoint.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/filter/JwtAuthenticationFilter.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/provider/JwtTokenizer.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/refreshToken/RefreshToken.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/refreshToken/RefreshTokenRepository.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/service/AuthService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/service/CustomUserDetailsService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/utils/SecurityUtil.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/controller/UserController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/UserPostDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/entity/User.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/mapper/UserMapper.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/service/UserService.java
  server/catvillage/src/main/resources/application.yml
Labels: 🌕 BE, 💡 FEAT

#92 fix: security 설정 수정
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/config/SecurityConfig.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/provider/JwtTokenizer.java
Labels: 🌕 BE, 🐞 BUG, 🔧 FIX

#102 feat: 배포 자동화 설정 파일 생성
  .github/workflows/client-auto-deploy.yml
Labels: 🖥 DEPLOY, ☀️ FE

#103 fix: User 카운트 관련 수정
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/UserGetResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/entity/User.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/mapper/UserMapper.java
Labels: 🌕 BE, 🔧 FIX

#127 feat: Picture 필수 클래스 및 저장 기능 구현
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/picture/entity/Picture.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/picture/repository/PictureRepository.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/picture/service/PictureService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/exception/ExceptionCode.java
Labels: 🌕 BE, 💡 FEAT, 🎯 REQUIRED

#128 fix: breed 관련 클래스 삭제
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/controller/CatController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/dto/BreedPostDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/dto/BreedResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/entity/Breed.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/entity/Cat.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/mapper/BreedMapper.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/mapper/CatMapper.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/repository/BreedRepository.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/service/BreedService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/service/CatService.java
Labels: 🌕 BE, 🔧 FIX, 🎯 REQUIRED

#129 feat: 집사생활 필수 클래스 생성
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/controller/BoardController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/BoardPostDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/BoardPostResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/entity/Board.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/mapper/BoardMapper.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/repository/BoardRepository.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/service/BoardService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/picture/entity/Picture.java
Labels: 🌕 BE, 💡 FEAT, 🎯 REQUIRED

#132 feat: Board comment 및 Board Tag 관련 클래스 추가
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/controller/BoardController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/entity/Board.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/entity/BoardComment.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/entity/BoardTag.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/entity/TagToBoard.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/entity/TagToBoardId.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/repository/BoardCommentRepository.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/repository/BoardTagRepository.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/repository/TagToBoardRepository.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/service/BoardCommentService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/service/BoardService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/service/BoardTagService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/service/TagToBoardService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/picture/entity/Picture.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/entity/Follow.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/entity/User.java
Labels: 🌕 BE, 💡 FEAT, 🎯 REQUIRED

#134 feat: 로그인 화면 마크업
  client/src/assets/kakao-login.png
  client/src/components/modules/SocialLoginButton/SocialLoginButton.tsx
  client/src/components/modules/SocialLoginButton/index.ts
  client/src/pages/Login/Login.style.ts
  client/src/pages/Login/Login.tsx
  client/src/pages/Login/index.ts
Labels: ☀️ FE, 💡 FEAT, 🎯 REQUIRED

#135 feat: 회원가입 화면 마크업
  client/src/pages/Signup/Signup.style.ts
  client/src/pages/Signup/Signup.tsx
  client/src/pages/Signup/index.ts
Labels: ☀️ FE, 💡 FEAT, 🎯 REQUIRED

#136 feat: ContentInput 마크업
  client/src/components/atoms/ContentInput/ContentInput.style.tsx
  client/src/components/atoms/ContentInput/ContentInput.tsx
  client/src/components/atoms/ContentInput/inedx.ts
Labels: ☀️ FE, 💡 FEAT

#140 style: prettier 적용
  client/.babelrc
  client/.eslintrc.js
  client/.prettierrc.js
  client/src/App.tsx
  client/src/assets/icons/index.tsx
  client/src/components/atoms/Button/Button.tsx
  client/src/routes/routes.ts
Labels: ☀️ FE, 💄 STYLE

#139 fix: style폴더 path-alias 오타 수정
  client/tsconfig.json
Labels: 🐞 BUG, ☀️ FE, 🔧 FIX

#141 feat: '고양이 등록하기' 기능 구현 및 '고양이 수정하기' 기능 수정
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/controller/CatController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/dto/CatResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/mapper/CatTagMapper.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/repository/TagToCatRepository.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/service/CatService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/service/CatTagService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/exception/ExceptionCode.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/service/UserService.java
Labels: 🌕 BE, 🐞 BUG, 💡 FEAT, 🎯 REQUIRED

#145 Feat/swagger config
  .gitignore
  server/catvillage/build.gradle
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/config/SwaggerConfig.java
Labels: 🌕 BE, 📄 DOCS

#146 feat: Swagger API 명세에 들어갈 설명 코드 추가
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/controller/BoardController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/controller/CatController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/config/SwaggerConfig.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/controller/FeedController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/controller/AuthController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/controller/UserController.java
Labels: 🌕 BE, 📄 DOCS, ⚙️ REFACTOR

#147 Feat: 냥이생활 피드에 관련된 template들 추가
  client/src/assets/icons/camera.svg
  client/src/assets/icons/index.tsx
  client/src/components/atoms/ContentInput/inedx.ts
  client/src/components/atoms/Input/Input.style.tsx
  client/src/components/modules/FormTextInput/FormTextInput.style.tsx
  client/src/components/modules/FormTextInput/FormTextInput.tsx
  client/src/components/modules/FormTextInput/index.ts
  client/src/components/modules/ImageInput/ImageInput.style.tsx
  client/src/components/modules/ImageInput/ImageInput.tsx
  client/src/components/modules/ImageInput/index.ts
  client/src/components/template/FeedDetail/FeedDetail.style.tsx
  client/src/components/template/FeedDetail/FeedDetail.tsx
  client/src/components/template/FeedDetail/index.ts
  client/src/components/template/FeedForm/FeedForm.style.tsx
  client/src/components/template/FeedForm/FeedForm.tsx
  client/src/components/template/FeedForm/index.ts
Labels: ☀️ FE, 💡 FEAT

#149 feat: spring에 S3로 파일 업로드 코드 구현
  .github/workflows/PR-build.yml
  server/catvillage/build.gradle
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/entity/Cat.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/picture/controller/FileUploadController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/picture/dto/PictureDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/picture/entity/Picture.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/picture/service/S3UploadService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/config/aws/AwsConfig.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/entity/Feed.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/entity/FeedComment.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/entity/User.java
  server/catvillage/src/main/resources/application.yml
Labels: 🌕 BE, 💡 FEAT, 🎯 REQUIRED

#156 feat: 냥이생활 특정 피드 정보 불러오기 요청 기능 구현 및 로그인 에러 fix
  .github/workflows/PR-build.yml
  .github/workflows/auto-build.yml
  .gitignore
  scripts/deploy.sh
  server/catvillage/build.gradle
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/entity/Cat.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/picture/dto/PictureDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/exception/ExceptionCode.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/controller/FeedController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/dto/FeedCommentGetDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/dto/FeedCommentPostDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/dto/FeedGetResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/entity/FeedComment.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/mapper/FeedCommentMapper.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/mapper/FeedMapper.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/mapper/FeedTagMapper.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/repository/FeedCommentRepository.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/service/FeedCommentService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/service/FeedService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/service/FeedTagService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/config/SecurityConfig.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/dto/UserRequestDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/refreshToken/RefreshToken.java
  server/catvillage/src/main/resources-dev/application.yml
  server/catvillage/src/main/resources-prod/application.yml
  server/catvillage/src/main/resources/application-common.yml
Labels: 🌕 BE, 🐞 BUG, 💡 FEAT, 🎯 REQUIRED

#158 feat: 회원가입 유효성 검사 구현
  client/package-lock.json
  client/package.json
  client/src/components/atoms/Input/Input.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/Signup/Signup.style.ts
  client/src/pages/Signup/Signup.tsx
Labels: ☀️ FE, 💡 FEAT

#160 feat: 집사생활 게시글 삭제 기능 구현
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/controller/BoardController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/service/BoardService.java
Labels: 🌕 BE, 💡 FEAT, 🎯 REQUIRED

#161 fix: 집사생활 등록 및 수정시 사용되는 DTO 수정
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/BoardPatchDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/BoardPostDto.java
Labels: 🌕 BE, 🔧 FIX

#162 feat: 집사생활 전체 및 특정 게시글 보기 기능 구현
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/controller/BoardController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/BoardCommentResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/BoardGetResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/BoardMultiGetResponse.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/BoardUserCommentResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/mapper/BoardCommentMapper.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/mapper/BoardMapper.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/service/BoardService.java
Labels: 🌕 BE, 💡 FEAT, 🎯 REQUIRED

#165 chore: 기본 프로필 이미지 교체
  client/src/assets/default-profile.jpeg
  client/src/assets/default-profile.png
Labels: ☀️ FE, 🔧 FIX

#163 feat: react-router-dom 사용 관련 변경사항
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/layout/DashBoard.tsx
  client/src/layout/Iphone11ProLayout.tsx
  client/src/pages/Board/BoardDetail/BoardDetail.tsx
  client/src/pages/Board/BoardDetail/index.ts
  client/src/pages/Board/Boards/Boards.tsx
  client/src/pages/Board/Boards/index.ts
  client/src/pages/Board/EditBoard/EditBoard.tsx
  client/src/pages/Board/EditBoard/index.ts
  client/src/pages/Board/NewBoard/NewBoard.tsx
  client/src/pages/Board/NewBoard/index.tsx
  client/src/pages/Feed/EditFeed/EditFeed.tsx
  client/src/pages/Feed/EditFeed/index.ts
  client/src/pages/Feed/FeedDetail/FeedDetail.tsx
  client/src/pages/Feed/FeedDetail/index.ts
  client/src/pages/Feed/Feeds/Feeds.tsx
  client/src/pages/Feed/Feeds/index.ts
  client/src/pages/Feed/NewFeed/NewFeed.tsx
  client/src/pages/Feed/NewFeed/index.ts
  client/src/routes/AppRoutes.tsx
  client/src/routes/board.routes.tsx
  client/src/routes/error.routes.tsx
  client/src/routes/feed.routes.tsx
  client/src/routes/index.ts
  client/src/routes/routes.ts
  client/webpack/webpack.dev.js
Labels: ☀️ FE, 💡 FEAT

#164 fix: github secrets not working fix
  .github/workflows/PR-build.yml
  .github/workflows/auto-build.yml
  server/catvillage/src/main/resources-prod/application.yml
Labels: 🖥 DEPLOY, 🔧 FIX, ⚙️ REFACTOR

#166 feat: 냥이생활 전체 피드 보기 기능 구현
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/picture/dto/PictureDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/controller/FeedController.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/dto/FeedMultiGetResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/dto/FeedMultiResponseDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/dto/FeedPostDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/dto/FeedTagDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/mapper/FeedMapper.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/service/FeedService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/controller/FollowService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/FollowFeedGetDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/repository/FollowRepository.java
Labels: 🌕 BE, 💡 FEAT, 🎯 REQUIRED

#169 fix: post 시 복합 PK 부분 에러 fix 및 고양이 등록시 성별 에러 fix
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/entity/TagToBoardId.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/dto/CatPostDto.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/entity/TagToCatId.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/service/CatService.java
  server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/entity/TagToFeedId.java
Labels: 🌕 BE, 🐞 BUG
